version: '3.7'

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  app:
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    image: gnu96/multiarch-cross-compilation:latest
    container_name: app
    ports:
      - "8080:8080"
    logging: *logging